# Generated by Django 5.1.6 on 2025-02-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_kibaru_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='skills',
            field=models.ManyToManyField(to='_kibaru_api.skills'),
        ),
    ]
