# Generated by Django 5.1.6 on 2025-07-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_kibaru_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='certificate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
